<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-11-21T19:22:19 IST" name="Default suite" finished-at="2023-11-21T19:22:50 IST" duration-ms="30974">
    <groups>
    </groups>
    <test started-at="2023-11-21T19:22:19 IST" name="Default test" finished-at="2023-11-21T19:22:50 IST" duration-ms="30974">
      <class name="seleniumtasks.ScreenshotOnFailureTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:seleniumtasks.ScreenshotOnFailureTest@399f45b1]" started-at="2023-11-21T19:22:19 IST" name="setUp" finished-at="2023-11-21T19:22:22 IST" duration-ms="2811" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="emptyFieldsTest()[pri:0, instance:seleniumtasks.ScreenshotOnFailureTest@399f45b1]" started-at="2023-11-21T19:22:22 IST" name="emptyFieldsTest" finished-at="2023-11-21T19:22:27 IST" duration-ms="4490" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://katalon-demo-cura.herokuapp.com/#appointment] but found [https://katalon-demo-cura.herokuapp.com/profile.php#login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://katalon-demo-cura.herokuapp.com/#appointment] but found [https://katalon-demo-cura.herokuapp.com/profile.php#login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at seleniumtasks.ScreenshotOnFailureTest.emptyFieldsTest(ScreenshotOnFailureTest.java:52)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emptyFieldsTest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:seleniumtasks.ScreenshotOnFailureTest@399f45b1]" started-at="2023-11-21T19:22:27 IST" name="tearDown" finished-at="2023-11-21T19:22:27 IST" duration-ms="883" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=emptyFieldsTest status=FAILURE method=ScreenshotOnFailureTest.emptyFieldsTest()[pri:0, instance:seleniumtasks.ScreenshotOnFailureTest@399f45b1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:seleniumtasks.ScreenshotOnFailureTest@399f45b1]" started-at="2023-11-21T19:22:27 IST" name="setUp" finished-at="2023-11-21T19:22:29 IST" duration-ms="1478" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="invalidLoginTest()[pri:0, instance:seleniumtasks.ScreenshotOnFailureTest@399f45b1]" started-at="2023-11-21T19:22:29 IST" name="invalidLoginTest" finished-at="2023-11-21T19:22:33 IST" duration-ms="3838" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://katalon-demo-cura.herokuapp.com/#appointment] but found [https://katalon-demo-cura.herokuapp.com/profile.php#login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://katalon-demo-cura.herokuapp.com/#appointment] but found [https://katalon-demo-cura.herokuapp.com/profile.php#login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at seleniumtasks.ScreenshotOnFailureTest.invalidLoginTest(ScreenshotOnFailureTest.java:46)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLoginTest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:seleniumtasks.ScreenshotOnFailureTest@399f45b1]" started-at="2023-11-21T19:22:33 IST" name="tearDown" finished-at="2023-11-21T19:22:34 IST" duration-ms="706" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=invalidLoginTest status=FAILURE method=ScreenshotOnFailureTest.invalidLoginTest()[pri:0, instance:seleniumtasks.ScreenshotOnFailureTest@399f45b1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:seleniumtasks.ScreenshotOnFailureTest@399f45b1]" started-at="2023-11-21T19:22:34 IST" name="setUp" finished-at="2023-11-21T19:22:35 IST" duration-ms="1266" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validLoginTest()[pri:0, instance:seleniumtasks.ScreenshotOnFailureTest@399f45b1]" started-at="2023-11-21T19:22:35 IST" name="validLoginTest" finished-at="2023-11-21T19:22:49 IST" duration-ms="13872" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:seleniumtasks.ScreenshotOnFailureTest@399f45b1]" started-at="2023-11-21T19:22:49 IST" name="tearDown" finished-at="2023-11-21T19:22:50 IST" duration-ms="1530" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLoginTest status=SUCCESS method=ScreenshotOnFailureTest.validLoginTest()[pri:0, instance:seleniumtasks.ScreenshotOnFailureTest@399f45b1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- seleniumtasks.ScreenshotOnFailureTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
